[package]
name = "file-rotate"
version = "0.2.0"
authors = ["Kevin Robert Stravers <macocio@gmail.com>"]
edition = "2018"
description = "Log rotation for files"
homepage = "https://github.com/BourgondAries/file-rotate"
repository = "https://github.com/BourgondAries/file-rotate"
keywords= ["log", "rotate", "logrotate"]
license = "LGPL-3.0-or-later"

[features]
async = ["futures", "futures-util", "tokio"]

[dependencies]
futures = { version = "0.3.8", optional = true }
futures-util = { version = "0.3.8", optional = true }
tokio = { version = "0.3.6", features = ["rt-multi-thread", "macros", "time", "fs", "io-util", "stream"], optional = true }


[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
assert_matches = "1.4.0"
